### ISSUE TITLE
`body` and `p` shouldn't have the font set to heading-font

### ISSUE THREAD

**Issue by kumarharsh** [playlyfe/aegis#2]
``` scss
h1, h2, h3, h4, h5, h6, p, body, textarea, input, select {
  font-family: $heading-font-family;
  font-weight: normal;
}
```

What the hell? What were you thinking? Split it out.
